/// Marks every XML file the generator writes.
///
/// It is what makes a re-run safe: a resource carrying this line came from an
/// earlier run and can be replaced or deleted, whatever it is called, so
/// renaming the drawable does not leave the old one behind in the APK.
const stamp = '<!-- Generated by android_avd_splash. Edits here are overwritten. -->';

/// The declaration and the stamp, which every generated XML file starts with.
const xmlHeader = '<?xml version="1.0" encoding="utf-8"?>\n$stamp\n';
